packages:
  - 'packages/*'
  - 'playground/**'

catalog:
  'vue': ^3.5.26
  'vite': npm:@voidzero-dev/vite-plus-core@latest
  'vue-router': ^4.6.4
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  '@voidzero-dev/vite-plus': latest

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.3.0

overrides:
  '@vitejs/plugin-vue': workspace:*
  vite: 'catalog:'
  vitest: 'catalog:'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - less

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver

hoistPattern:
  - postcss
  - pug # playground/vue > @vue/compiler-sfc
  - ts-node # playground/tailwind

autoInstallPeers: false

strictPeerDependencies: false

shellEmulator: true
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
